export const SCREEN_NAMES = {
  onboarding: 'onboarding',
  splash: 'splash',
  login: 'login',
  register: 'register',
  registerTwo: 'registerTwo',
  confirmRegistration: 'confirmRegistration',
  successRegistration: 'successRegistratoin',
  home: 'home',
  activityTracker: 'activityTracker',
  workoutTracker: 'workoutTracker',
  workoutDetilsOne: 'workoutDetilsOne',
  workoutDetailsTwo: 'workoutDetailsTwo',
  workoutSchedule: 'workoutSchedule',
  addSchedule: 'addSchedule',
  sleepTracker: 'sleepTracker',
  sleepSchedule: 'sleepSchedule',
  addSleepSchedule: 'addSleepSchedule',
  progressPhoto: 'progressPhoto',
  comparePhoto: 'comparePhoto',
  choosePhoto: 'choosePhoto',
  profile: 'profile',
  editProfile: 'editProfile',
  forgetPassword: 'forgetPassword',
  bottomTab: 'bottomTab',
};
